# 🗂️ 마음서랍 채널 브랜딩 설정
# 생성일: 2025-08-20
# 용도: YouTube 채널 브랜딩 자산 중앙 관리

channels:
  maeum-seorab:
    # 기본 채널 정보
    name: "마음서랍"
    concept: "마음속 깊이 간직한 이야기들을 꺼내어 나누는 공간"
    target_audience: "인생 경험이 풍부한 시니어층"
    
    # YouTube 채널 페이지 소개글 (채널 About 섹션용)
    about_description: |
      🌸 마음을 담아 전하는 우리 세대 이야기

      그 시절을 함께 걸어온 분들이라면 누구나 공감할 수 있는
      진솔하고 따뜻한 인생 이야기를 들려드립니다.

      💝 어떤 이야기를 들려드리나요?

      ✨ 시집살이부터 자녀 교육까지, 우리가 겪어온 진짜 이야기
      ✨ 1960년대부터 2020년대까지, 시대별 생생한 경험담
      ✨ 여성과 남성, 각자의 삶에서 우러나온 솔직한 회상
      ✨ 혼자가 아니라는 걸 느낄 수 있는 따뜻한 공감의 시간

      🎯 이런 분들께 추천해요

      • 인생의 쓴맛과 단맛을 모두 아시는 분
      • 진짜 이야기, 진짜 감정을 소중히 여기시는 분
      • 때로는 웃고, 때로는 눈시울이 붉어져도 괜찮다고 생각하시는 분
      • 나이를 먹는다는 게 외롭지 않다는 걸 함께 느끼고 싶으신 분
      • 우리 세대만의 애환과 지혜를 나누고 싶으신 분

      🌟 채널의 특별함

      💌 시청자분들이 보내주신 소중한 경험담을 바탕으로 정성껏 각색
      🎨 그 시절 특유의 정서와 미묘한 감정까지 놓치지 않으려 노력
      🤝 세대를 아우르는 진정성 있는 소통과 공감의 장
      🔔 구독하시면 우리 세대의 소중한 이야기들을 놓치지 않고 함께하실 수 있어요
      💬 댓글로 여러분의 이야기도 들려주세요 - 모든 목소리가 소중합니다

      #우리세대 #진솔한이야기 #인생이야기 #마음공감 #어르신 #세대공감 #한국시니어 #삶의이야기 #진정성 #따뜻한소통
    
    # 영상 설명 자동 추가용 푸터 (기존 DESCRIPTION_FOOTER)
    video_footer: |
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

      🗂️ 마음서랍에서 꺼내드리는 진솔한 이야기

      시청자분이 용기 내어 보내주신 소중한 경험담을 바탕으로
      마음서랍 깊숙한 곳에서 정성껏 꺼내어 준비한 이야기입니다.

      그 시절을 함께 걸어온 우리이기에 알 수 있는 아픔과 기쁨,
      말로 다 표현할 수 없는 그 미묘한 감정들까지
      마음서랍에 고이 간직하며 만들었습니다.

      📢 창작물 보호 안내
      이 영상의 대본과 모든 내용은 저작권 보호를 받습니다.
      무단 복제나 상업적 이용은 정중히 사양합니다.

      🗂️ 진심으로 나누고 싶은 마음서랍 이야기들

      혹시 보시면서 "아, 나도 그런 마음 있었는데..." 하고 고개를 끄덕이셨나요?
      아니면 "그 마음 정말 이해해..." 하며 마음이 먹먹해지셨나요?

      그런 순간들이 바로 제가 마음서랍을 여는 이유입니다.
      우리는 혼자가 아니에요. 비슷한 마음을 품고 살아온 분들이 이렇게 많이 계시니까요.

      💝 **구독**해 주시면 → 계속해서 마음서랍에서 꺼낸 진솔한 이야기들을 들려드릴 수 있어요
      👍 **좋아요** 하나가 → 다른 분들께도 이 따뜻한 공감을 전해드릴 수 있답니다
      💬 **댓글**이 정말 힘이 돼요 → "맞아요", "공감돼요" 이런 짧은 말 한마디도 큰 위로가 됩니다
      🔔 **알림**을 켜두시면 → 새로운 마음서랍 이야기가 올라올 때마다 함께하실 수 있어요

      만약 이 이야기가 마음에 닿으셨다면,
      아마 이런 분이실 거예요:

      • 인생의 쓴맛과 단맛을 모두 아시는 분
      • 진짜 이야기, 진짜 감정을 소중히 여기시는 분
      • 때로는 웃고, 때로는 눈시울이 붉어져도 괜찮다고 생각하시는 분
      • 나이를 먹는다는 게 외롭지 않다는 걸 함께 느끼고 싶으신 분

      앞으로도 마음을 다해 정성스럽게 마음서랍을 열어드리겠습니다.
      함께해 주셔서 고맙습니다.

      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    
    # 기본 태그 설정 (SEO 최적화)
    default_tags:
      - "마음서랍"
      - "진솔한이야기"
      - "인생이야기"
      - "마음공감"
      - "정성스런이야기"
      - "어르신"
      - "세대공감"
      - "진심담백"
      - "인생경험"
      - "함께하는이야기"
      - "따뜻한소통"
      - "한국시니어"
      - "마음나누기"
      - "진정성"
      - "삶의이야기"
      - "마음속이야기"
    
    # YouTube API 설정
    youtube_settings:
      category_id: 24               # Entertainment
      default_privacy: "private"    # 기본 공개 설정
      default_language: "ko"        # 한국어
      audio_language: "ko"          # 오디오 언어

# 향후 채널 확장을 위한 템플릿 (주석 처리)
# future-channel:
#   name: "새채널명"
#   about_description: |
#     새 채널 소개글...
#   video_footer: |
#     새 채널 영상 푸터...
#   default_tags:
#     - "새채널태그"
#   youtube_settings:
#     category_id: 24
#     default_privacy: "private"