"""Auto migration

Revision ID: 8d1516ddf044
Revises: 14aedf8664eb
Create Date: 2025-08-18 20:49:18.366122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1516ddf044'
down_revision: Union[str, Sequence[str], None] = '14aedf8664eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('audio_file_path', sa.String(length=500), nullable=True))
    op.add_column('scripts', sa.Column('srt_file_path', sa.String(length=500), nullable=True))
    op.add_column('scripts', sa.Column('audio_duration', sa.Float(), nullable=True))
    op.add_column('scripts', sa.Column('tts_voice', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'tts_voice')
    op.drop_column('scripts', 'audio_duration')
    op.drop_column('scripts', 'srt_file_path')
    op.drop_column('scripts', 'audio_file_path')
    # ### end Alembic commands ###
