"""Remove TTS fields from scripts table

Revision ID: d6fd082abbaa
Revises: 8d1516ddf044
Create Date: 2025-08-18 23:54:16.788701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6fd082abbaa'
down_revision: Union[str, Sequence[str], None] = '8d1516ddf044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'srt_file_path')
    op.drop_column('scripts', 'tts_voice')
    op.drop_column('scripts', 'audio_file_path')
    op.drop_column('scripts', 'audio_duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('audio_duration', sa.FLOAT(), nullable=True))
    op.add_column('scripts', sa.Column('audio_file_path', sa.VARCHAR(length=500), nullable=True))
    op.add_column('scripts', sa.Column('tts_voice', sa.VARCHAR(length=50), nullable=True))
    op.add_column('scripts', sa.Column('srt_file_path', sa.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
